[tool.ruff]
line-length = 88
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
  "D",   # pydocstyle
  "PT",  # flake8-pytest-style
]
exclude = [
    ".git",
    "__pycache__",
]

[tool.ruff.mccabe]
max-complexity = 10